version: '3.7'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: future417  # required, replace with your desired root password.
      MYSQL_USER: test
      MYSQL_PASSWORD: future417
      MYSQL_DATABASE: test
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db